language: javascript

install:
  - cd package/
  - npm install

script:
  - cd package/
  - npm run build
  - npm test

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
