language: javascript

install:
  - cd package/
  # newer npm spinner is just a pain and will mess up in the logfiles
  - npm config set spin=false
  - npm install

script:
  # the working dir is re-used from the 'install' phase, no need to switch dirs here

  - npm run build

  # for tests, we'd need a crossbario instance :(
  # - npm test

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
